# Generated by Django 2.2.6 on 2019-12-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='main_class',
            field=models.CharField(choices=[('Barbarian', 'Barbarian'), ('Bard', 'Bard'), ('Cleric', 'Cleric'), ('Druid', 'Druid'), ('Fighter', 'Fighter'), ('Monk', 'Monk'), ('Paladin', 'Paladin'), ('Ranger', 'Ranger'), ('Rogue', 'Rogue'), ('Sorcerer', 'Sorcerer'), ('Warlock', 'Warlock'), ('Wizard', 'Wizard')], default='Fighter', max_length=25),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.CharField(choices=[('Drow', 'Drow'), ('Dwarf', 'Dwarf'), ('Elf', 'Elf'), ('Half Elf', 'Half Elf'), ('Half Orc', 'Half Orc'), ('Halfling', 'Halfling'), ('Human', 'Human'), ('Warforged', 'Warforged')], default='Human', max_length=25),
        ),
    ]
